const menu = [
  	{
		id: 1,
		title: 'Spicy Chicken Feet Stew',
		category: 'entree',
		price: 19.99,
		img: './images/img1.png',
		desc: '새마을 국물 닭발',
	},
	{
		id: 2,
		title: 'Korean Market Style Chicken',
		category: 'entree',
		price: 19.99,
		img: './images/img2.png',
		desc: '시장 통닭',
	},
	{
		id: 3,
		title: 'Rose Tteok bok ki',
		category: 'entree',
		price: 17.99,
		img: './images/img3.png',
		desc: '로제 떡볶이',
	},
	{
		id: 4,
		title: 'Traditional Tteok bok ki',
		category: 'entree',
		price: 17.99,
		img: './images/img4.png',
		desc: '국민학교 떡볶이',
	},
	{
		id: 5,
		title: 'New village Spicy Tteok bok ki w/ cheese',
		category: 'entree',
		price: 19.99,
		img: './images/img5.png',
		desc: '새마을 떡볶이',
	},
	{
		id: 6,
		title: 'Stir Fried Squid',
		category: 'entree',
		price: 17.99,
		img: './images/img6.png',
		desc: '오징어 볶음',
	},
	{
		id: 7,
		title: 'Sea Snail and Squid Muchim',
		category: 'entree',
		price: 29.99,
		img: './images/img7.png',
		desc: '오뱅이',
	},
	{
		id: 8,
		title: 'Jokbal, Braised Pig Trotter',
		category: 'entree',
		price: 32.99 ,
		img: './images/img8.png',
		desc: '족발',
	},
	{
		id: 9,
		title: 'Bossam,Korean Pork Lettuce Wrap',
		category: 'entree',
		price: 32.99,
		img: './images/img9.png',
		desc: '보쌈',
	},
	{
		id: 10,
		title: '곱창막창염통',
		category: 'entree',
		price: 23.99,
		img: './images/img10.png',
		desc: '곱막염 (Beef Intestines, Tribe and Heart)',
	},
	{
		id: 11,
		title: ' Spicy Stir fried Tripe and Large Intestines',
		category: 'entree',
		price: 23.99,
		img: './images/img11.png',
		desc: '불양 대창 구이',
	},
	{
		id: 12,
		title: 'Beef Brisket with Stir Bean sprout',
		category: 'entree',
		price: 19.99,
		img: './images/img12.png',
		desc: '차돌박이 숙주볶음',
	},
	{
		id: 13,
		title: 'Tofu with Stir fried kimchi and Pork',
		category: 'entree',
		price: 19.99,
		img: './images/img13.png',
		desc: '두부김치',
	},
	{
		id: 14,
		title: 'Bulgogi',
		category: 'entree',
		price: 19.99,
		img: './images/img14.png',
		desc: '불고기',
	},
	{
		id: 15,
		title: 'Spicy Stir fried Pork',
		category: 'entree',
		price: 17.99,
		img: './images/img15.png',
		desc: '제육볶음',
	},
	{
		id: 16,
		title: 'Chicken Gizzard',
		category: 'entree',
		price: 17.99,
		img: './images/img16.png',
		desc: '화생방 닭똥집',
	},
	{
		id: 17,
		title: 'Seafood Korean Pancake',
		category: 'entree',
		price: 15.99,
		img: './images/img17.png',
		desc: '해물파전',
	},
	{
		id: 18,
		title: 'Kimchi Korean Pancake',
		category: 'entree',
		price: 14.99,
		img: './images/img18.png',
		desc: '김치전',
	},
	{
		id: 19,
		title: 'Stir Fried Sausage and Vegetable',
		category: 'entree',
		price: 14.99,
		img: './images/img19.png',
		desc: '소세지 야채볶음',
	},
	{
		id: 20,
		title: 'Popcorn Chicken',
		category: 'entree',
		price: 14.99,
		img: './images/img20.png',
		desc: '팝콘치킨',
	},
	{
		id: 21,
		title: 'Korean Steamed Eggs with Cheese',
		category: 'entree',
		price: 12.99,
		img: './images/img21.png',
		desc: '치즈 계란찜',
	},
	{
		id: 22,
		title: 'Noodle in Cold Kimchi soup',
		category: 'entree',
		price: 12.99,
		img: './images/img22.png',
		desc: '김치말이국수',
	},
	{
		id: 23,
		title: 'Makguksu, Buckwheat Noodle in spicy cold broth',
		category: 'entree',
		price: 12.99,
		img: './images/img23.png',
		desc: '막국수',
	},
	{
		id: 24,
		title: 'Deep Fried filefish jerky',
		category: 'entree',
		price: 12.99,
		img: './images/img24.png',
		desc: '쥐포튀김',
	},
	{
		id: 25,
		title: 'Spam Kimchi Fried Rice with Fried Egg',
		category: 'entree',
		price: 9.99,
		img: './images/img25.png',
		desc: '스팸 김치볶음밥',
	},
	{
		id: 26,
		title: 'Silkworm Soup',
		category: 'entree',
		price: 9.99,
		img: './images/img26.png',
		desc: '번데기탕',
	},
	{
		id: 27,
		title: 'Mac & Corn Cheese',
		category: 'entree',
		price: 9.99,
		img: './images/img27.png',
		desc: '마카로니 콘치즈',
	},
	{
		id: 28,
		title: 'Fried Eggs with spam',
		category: 'entree',
		price: 9.99 ,
		img: './images/img28.png',
		desc: '스팸 계란후라이',
	},
	{
		id: 29,
		title: 'Truffle French Fries',
		category: 'entree',
		price: 9.99,
		img: './images/img29.png',
		desc: '트러플 감자튀김',
	},
	{
		id: 30,
		title: 'Onion Ring',
		category: 'entree',
		price: 8.99,
		img: './images/img30.png',
		desc: '양파링',
	},
	{
		id: 31,
		title: 'Mozzarella Cheese Stick',
		category: 'entree',
		price: 8.99,
		img: './images/img31.png',
		desc: '모짜렐라 치즈스틱',
	},
	{
		id: 32,
		title: 'Acorn Jelly in Cold Broth',
		category: 'entree',
		price: 7.99 ,
		img: './images/img32.png',
		desc: '묵사발',
	},
	{
		id: 33,
		title: 'Peach in Light Syrup',
		category: 'entree',
		price: 6.99,
		img: './images/img33.png',
		desc: '황도',
	},
	{
		id: 34,
		title: 'Fried Dumpling',
		category: 'entree',
		price: 6.99,
		img: './images/img34.png',
		desc: '군만두',
	},
	{
		id: 35,
		title: 'Dried Squid and Peanuts',
		category: 'entree',
		price: 16.99,
		img: './images/img35.png',
		desc: '마른오징어 땅콩',
	},
	{
		id: 36,
		title: 'Fruit Platter',
		category: 'entree',
		price: 19.99,
		img: './images/img36.png',
		desc: '과일안주',
	},
	{
		id: 37,
		title: 'Korean Spicy Chicken and Intestines Stew w/ Noodle',
		category: 'soup',
		price: 34.99,
		img: './images/img37.png',
		desc: '곱도리탕',
	},
	{
		id: 38,
		title: 'Tendon/Shank Soup',
		category: 'soup',
		price: 25.99,
		img: './images/img38.png',
		desc: '도가니 수육 전골',
	},
	{
		id: 39,
		title: 'Army Stew w/ Ramen noodle',
		category: 'soup',
		price: 24.99,
		img: './images/img39.png',
		desc: '부대찌개',
	},
	{
		id: 40,
		title: 'Seafood Jjampong w/ udon noodle',
		category: 'soup',
		price: 24.99,
		img: './images/img40.png',
		desc: '해물짬뽕탕',
	},
	{
		id: 41,
		title: 'Silken Tofu Stew with Beef',
		category: 'soup',
		price: 19.99,
		img: './images/img41.png',
		desc: '새마을 순두부 전골',
	},
	{
		id: 42,
		title: 'Mussel Soup',
		category: 'soup',
		price: 17.99,
		img: './images/img42.png',
		desc: '홍합탕',
	},
	{
		id: 43,
		title: 'Fishcake Soup',
		category: 'soup',
		price: 14.99,
		img: './images/img43.png',
		desc: '오뎅탕',
	},
	{
		id: 44,
		title: 'Malatang - Pork/Brisket',
		category: 'soup',
		price: 16.99,
		img: './images/img44.png',
		desc: '마라탕-돼지$5.99/차돌 $7.99',
	},
];
export default menu;
