const menu = [
  	{
		id: 1,
		title: '새마을 국물 닭발 (Spicy Chicken Feet Stew)',
		category: 'entree',
		price: 19.99,
		img: './images/img1.png',
		desc: 'food',
	},
	{
		id: 2,
		title: '시장 통닭 (Korean Market Style Chicken)',
		category: 'entree',
		price: 19.99,
		img: './images/img2.png',
		desc: 'food',
	},
	{
		id: 3,
		title: '로제 떡볶이 (Rose Tteok bok ki)',
		category: 'entree',
		price: 17.99,
		img: './images/img3.png',
		desc: 'food',
	},
	{
		id: 4,
		title: '국민학교 떡볶이 (Traditional Tteok bok ki)',
		category: 'entree',
		price: 17.99,
		img: './images/img4.png',
		desc: 'food',
	},
	{
		id: 5,
		title: '새마을 떡볶이 (New village Spicy Tteok bok ki w/ cheese)',
		category: 'entree',
		price: 19.99,
		img: './images/img5.png',
		desc: 'food',
	},
	{
		id: 6,
		title: '오징어 볶음 (Stir Fried Squid)',
		category: 'entree',
		price: 17.99,
		img: './images/img6.png',
		desc: 'food',
	},
	{
		id: 7,
		title: '오뱅이 (Sea Snail and Squid Muchim)',
		category: 'entree',
		price: 29.99,
		img: './images/img7.png',
		desc: 'food',
	},
	{
		id: 8,
		title: '족발 (Jokbal, Braised Pig Trotter)',
		category: 'entree',
		price: 32.99 ,
		img: './images/img8.png',
		desc: 'food',
	},
	{
		id: 9,
		title: '보쌈 (Bossam,Korean Pork Lettuce Wrap)',
		category: 'entree',
		price: 32.99,
		img: './images/img9.png',
		desc: 'food',
	},
	{
		id: 10,
		title: '곱막염 (곱창막창염통) (Beef Intestines, Tribe and Heart)',
		category: 'entree',
		price: 23.99,
		img: './images/img10.png',
		desc: 'food',
	},
	{
		id: 11,
		title: '불양 대창 구이 ( Spicy Stir fried Tripe and Large Intestines)',
		category: 'entree',
		price: 23.99,
		img: './images/img11.png',
		desc: 'food',
	},
	{
		id: 12,
		title: '차돌박이 숙주볶음 (Beef Brisket with Stir Bean sprout)',
		category: 'entree',
		price: 19.99,
		img: './images/img12.png',
		desc: 'food',
	},
	{
		id: 13,
		title: '두부김치 (Tofu with Stir fried kimchi and Pork)',
		category: 'entree',
		price: 19.99,
		img: './images/img13.png',
		desc: 'food',
	},
	{
		id: 14,
		title: '불고기 (Bulgogi)',
		category: 'entree',
		price: 19.99,
		img: './images/img14.png',
		desc: 'food',
	},
	{
		id: 15,
		title: '제육볶음 (Spicy Stir fried Pork)',
		category: 'entree',
		price: 17.99,
		img: './images/img15.png',
		desc: 'food',
	},
	{
		id: 16,
		title: '화생방 닭똥집 (Chicken Gizzard)',
		category: 'entree',
		price: 17.99,
		img: './images/img16.png',
		desc: 'food',
	},
	{
		id: 17,
		title: '해물파전 (Seafood Korean Pancake)',
		category: 'entree',
		price: 15.99,
		img: './images/img17.png',
		desc: 'food',
	},
	{
		id: 18,
		title: '김치전 (Kimchi Korean Pancake)',
		category: 'entree',
		price: 14.99,
		img: './images/img18.png',
		desc: 'food',
	},
	{
		id: 19,
		title: '소세지 야채볶음 (Stir Fried Sausage and Vegetable)',
		category: 'entree',
		price: 14.99,
		img: './images/img19.png',
		desc: 'food',
	},
	{
		id: 20,
		title: '팝콘치킨 (Popcorn Chicken)',
		category: 'entree',
		price: 14.99,
		img: './images/img20.png',
		desc: 'food',
	},
	{
		id: 21,
		title: '치즈 계란찜 (Korean Steamed Eggs with Cheese)',
		category: 'entree',
		price: 12.99,
		img: './images/img21.png',
		desc: 'food',
	},
	{
		id: 22,
		title: '김치말이국수 (Noodle in Cold Kimchi soup)',
		category: 'entree',
		price: 12.99,
		img: './images/img22.png',
		desc: 'food',
	},
	{
		id: 23,
		title: '막국수 (Makguksu, Buckwheat Noodle in spicy cold broth)',
		category: 'entree',
		price: 12.99,
		img: './images/img23.png',
		desc: 'food',
	},
	{
		id: 24,
		title: '쥐포튀김 (Deep Fried filefish jerky)',
		category: 'entree',
		price: 12.99,
		img: './images/img24.png',
		desc: 'food',
	},
	{
		id: 25,
		title: '스팸 김치볶음밥 (Spam Kimchi Fried Rice with Fried Egg)',
		category: 'entree',
		price: 9.99,
		img: './images/img25.png',
		desc: 'food',
	},
	{
		id: 26,
		title: '번데기탕 (Silkworm Soup)',
		category: 'entree',
		price: 9.99,
		img: './images/img26.png',
		desc: 'food',
	},
	{
		id: 27,
		title: '마카로니 콘치즈 (Mac & Corn Cheese)',
		category: 'entree',
		price: 9.99,
		img: './images/img27.png',
		desc: 'food',
	},
	{
		id: 28,
		title: '스팸 계란후라이 (Fried Eggs with spam)',
		category: 'entree',
		price: 9.99 ,
		img: './images/img28.png',
		desc: 'food',
	},
	{
		id: 29,
		title: '트러플 감자튀김 (Truffle French Fries)',
		category: 'entree',
		price: 9.99,
		img: './images/img29.png',
		desc: 'food',
	},
	{
		id: 30,
		title: '양파링 (Onion Ring)',
		category: 'entree',
		price: 8.99,
		img: './images/img30.png',
		desc: 'food',
	},
	{
		id: 31,
		title: '모짜렐라 치즈스틱 (Mozzarella Cheese Stick)',
		category: 'entree',
		price: 8.99,
		img: './images/img31.png',
		desc: 'food',
	},
	{
		id: 32,
		title: '묵사발 (Acorn Jelly in Cold Broth)',
		category: 'entree',
		price: 7.99 ,
		img: './images/img32.png',
		desc: 'food',
	},
	{
		id: 33,
		title: '황도 (Peach in Light Syrup)',
		category: 'entree',
		price: 6.99,
		img: './images/img33.png',
		desc: 'food',
	},
	{
		id: 34,
		title: '군만두 (Fried Dumpling)',
		category: 'entree',
		price: 6.99,
		img: './images/img34.png',
		desc: 'food',
	},
	{
		id: 35,
		title: '마른오징어 땅콩 (Dried Squid and Peanuts)',
		category: 'entree',
		price: 16.99,
		img: './images/img35.png',
		desc: 'food',
	},
	{
		id: 36,
		title: '과일안주 (Fruit Platter)',
		category: 'entree',
		price: 19.99,
		img: './images/img36.png',
		desc: 'food',
	},

	{
		id: 37,
		title: '곱도리탕 (Korean Spicy Chicken and Intestines Stew w/ Noodle)',
		category: 'soup',
		price: 34.99,
		img: './images/img37.png',
		desc: 'food',
	},
	{
		id: 38,
		title: '도가니 수육 전골 (Tendon/Shank Soup)',
		category: 'soup',
		price: 25.99,
		img: './images/img38.png',
		desc: 'food',
	},
	{
		id: 39,
		title: '부대찌개 (Army Stew w/ Ramen noodle)',
		category: 'soup',
		price: 24.99,
		img: './images/img39.png',
		desc: 'food',
	},
	{
		id: 40,
		title: '해물짬뽕탕 (Seafood Jjampong w/ udon noodle)',
		category: 'soup',
		price: 24.99,
		img: './images/img40.png',
		desc: 'food',
	},
	{
		id: 41,
		title: '새마을 순두부 전골 (Silken Tofu Stew with Beef)',
		category: 'soup',
		price: 19.99,
		img: './images/img41.png',
		desc: 'food',
	},
	{
		id: 42,
		title: '홍합탕 (Mussel Soup)',
		category: 'soup',
		price: 17.99,
		img: './images/img42.png',
		desc: 'food',
	},
	{
		id: 43,
		title: '오뎅탕 (Fishcake Soup)',
		category: 'soup',
		price: 14.99,
		img: './images/img43.png',
		desc: 'food',
	},
	{
		id: 44,
		title: '마라탕-돼지$5.99/차돌 $7.99',
		category: 'soup',
		price: 16.99,
		img: './images/img44.png',
		desc: 'food',
	},
];
export default menu;
